import type { NextConfig } from "next";

const CDN_URL = process.env.R2_CDN!;
const CDN_HOSTNAME = new URL(CDN_URL).hostname;

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "lvkydivstceibnjyndgo.supabase.co",
        pathname: "/storage/v1/object/**",
      },
      {
        protocol: "https",
        hostname: "*.public.blob.vercel-storage.com",
      },
      {
        protocol: "https",
        hostname: CDN_HOSTNAME,
      },
    ],
  },
  experimental: {
    serverActions: {
      bodySizeLimit: "5mb",
    },
  },

  async redirects() {
    return [
      { source: '/sekolah-kemurnian-1.html', destination: '/sekolah-kemurnian-1', permanent: true },
      { source: '/sekolah-kemurnian-2.html', destination: '/sekolah-kemurnian-2', permanent: true },
      { source: '/sekolah-kemurnian-3.html', destination: '/sekolah-kemurnian-3', permanent: true },
      { source: '/about.html', destination: '/about', permanent: true },
      { source: '/kurikulum-tk.html', destination: '/kurikulum/2', permanent: true },
      { source: '/kurikulum-tkbil.html', destination: '/kurikulum/3', permanent: true },
      { source: '/kurikulum-sd.html', destination: '/kurikulum/4', permanent: true },
      { source: '/kurikulum-smp.html', destination: '/kurikulum/5', permanent: true },
      { source: '/kurikulum-sma.html', destination: '/kurikulum/6', permanent: true },
      { source: '/kurikulum-english.html', destination: '/kurikulum/7', permanent: true },
      { source: '/news/2025/9_maulid.html', destination: '/news-detail/59', permanent: true },
      { source: '/news/2025/8_pameran_ite.html', destination: '/news-detail/58', permanent: true },
      { source: '/pelatihan2.html', destination: '/news-detail/57', permanent: true },
      { source: '/ajaranbaru.html', destination: '/news-detail/56', permanent: true },
      { source: '/open25.html', destination: '/news-detail/60', permanent: true },
      { source: '/O2sn1.html', destination: '/news-detail/61', permanent: true },
      { source: '/o2sn.html', destination: '/news-detail/62', permanent: true },
      { source: '/pelatihan1.html', destination: '/news-detail/55', permanent: true },
      { source: '/pelatihan.html', destination: '/news-detail/54', permanent: true },
      { source: '/news.html', destination: '/news', permanent: true },
      { source: '/promo-open-24.html', destination: '/enrollment', permanent: true },
      { source: '/index.php', destination: '/', permanent: true },
      { source: '/tk-kemurnian-1.html', destination: '/unit/tk-kemurnian-i', permanent: true },
      { source: '/sd-kemurnian-1.html', destination: '/unit/sd-kemurnian-i', permanent: true },
      { source: '/smp-kemurnian-1.html', destination: '/unit/smp-kemurnian-i', permanent: true },
      { source: '/tk-kemurnian-2.html', destination: '/unit/tk-kemurnian-ii', permanent: true },
      { source: '/sd-kemurnian-2.html', destination: '/unit/sd-kemurnian-ii', permanent: true },
      { source: '/smp-kemurnian-2.html', destination: '/unit/smp-kemurnian-ii', permanent: true },
      { source: '/sma-kemurnian-2.html', destination: '/unit/sma-kemurnian-ii', permanent: true },
      { source: '/tk-kemurnian-3.html', destination: '/unit/tk-kemurnian-iii', permanent: true },
      { source: '/sd-kemurnian-3.html', destination: '/unit/sd-kemurnian-iii', permanent: true },
      { source: '/Award_Qmur.html', destination: '/news-detail/30', permanent: true },
      { source: '/P5smp24.html', destination: '/news-detail/29', permanent: true },
      { source: '/Fieldtriptk24.html', destination: '/news-detail/63', permanent: true },
      { source: '/openqmur1.html', destination: '/news-detail/53', permanent: true },
      { source: '/openqmur.html', destination: '/news-detail/52', permanent: true },
      { source: '/kmnnew.html', destination: '/news-detail/51', permanent: true },
      { source: '/gradu.html', destination: '/news-detail/50', permanent: true },
      { source: '/binus.html', destination: '/news-detail/49', permanent: true },
      { source: '/sma_negeri2.html', destination: '/news-detail/64', permanent: true },
      { source: '/sma_negeri1.html', destination: '/news-detail/48', permanent: true },
      { source: '/29mei.html', destination: '/news-detail/47', permanent: true },
      { source: '/sma_nia.html', destination: '/news-detail/46', permanent: true },
      { source: '/grad_sma.html', destination: '/news-detail/45', permanent: true },
      { source: '/pidato_smp.html', destination: '/news-detail/44', permanent: true },
      { source: '/pidato_sd.html', destination: '/news-detail/43', permanent: true },
      { source: '/pidato_sd1.html', destination: '/news-detail/42', permanent: true },
      { source: '/smap_1.html', destination: '/news-detail/41', permanent: true },
      { source: '/smaptn1.html', destination: '/news-detail/40', permanent: true },
      { source: '/smaptn.html', destination: '/news-detail/39', permanent: true },
      { source: '/padus.html', destination: '/news-detail/38', permanent: true },
      { source: '/TK_baksos.html', destination: '/news-detail/36', permanent: true },
      { source: '/sma_dance.html', destination: '/news-detail/37', permanent: true },
      { source: '/sma_rrc2.html', destination: '/news-detail/35', permanent: true },
      { source: '/sma_rrc.html', destination: '/news-detail/34', permanent: true },
      { source: '/smap1.html', destination: '/news-detail/33', permanent: true },
      { source: '/smp2.html', destination: '/news-detail/32', permanent: true },
      { source: '/sdp1.html', destination: '/news-detail/31', permanent: true },
      { source: '/seminar-bahasa-kasih-sd.html', destination: '/news-detail/28', permanent: true },
      { source: '/promo-open-house.html', destination: '/news-detail/65', permanent: true },
      { source: '/graduation-day-sd-kmn3-2023.html', destination: '/news', permanent: true },
      { source: '/graduation-day-sd-kmn2-2023.html', destination: '/news', permanent: true },
      { source: '/graduation-day-sd-kmn1-2023.html', destination: '/news', permanent: true },
      { source: '/graduation-day-smp-kmn2-2023.html', destination: '/news', permanent: true },
      { source: '/graduation-day-smp-kmn1-2023.html', destination: '/news', permanent: true },
      { source: '/pengumuman-kelulusan-sd-kmn2-2023.html', destination: '/news', permanent: true },
      { source: '/pesta-akhir-tahun-tk-kmn2-2023.html', destination: '/news', permanent: true },
      { source: '/supermi-gpp-2023.html', destination: '/news', permanent: true },
      { source: '/graduation-day-tk-kmn3-2023.html', destination: '/news', permanent: true },
      { source: '/graduation-day-tk-kmn2-2023.html', destination: '/news', permanent: true },
      { source: '/graduation-day-tk-kmn1-2023.html', destination: '/news', permanent: true },
      { source: '/seminar-jajanan-sehat.html', destination: '/news', permanent: true },
      { source: '/ibadah_waisak_tk_sd_kmn2_2023.html', destination: '/news', permanent: true },
      { source: '/graduation-day-sma-kmn2-2023.html', destination: '/news', permanent: true },
      { source: '/ibadah_paskah-2023.html', destination: '/news', permanent: true },
      { source: '/buka_bersama-2023.html', destination: '/news', permanent: true },
      { source: '/pesantren_kilat-2023.html', destination: '/news', permanent: true },
      { source: '/fieldtrip-smp-2023.html', destination: '/news', permanent: true },
      { source: '/fieldtrip-sd-2023.html', destination: '/news', permanent: true },
      { source: '/pendalamaniman.html', destination: '/news', permanent: true },
      { source: '/valentine-sma.html', destination: '/news', permanent: true },
      { source: '/bahasakasih.html', destination: '/news', permanent: true },
      { source: '/qlive-2023.html', destination: '/news', permanent: true },
      { source: '/osis-sma-2023.html', destination: '/news', permanent: true },
      { source: '/seminar-mykids-mylegacy.html', destination: '/news', permanent: true },
      { source: '/osis-smp-2023.html', destination: '/news', permanent: true },
      { source: '/q-lead-2023.html', destination: '/news', permanent: true },
      { source: '/my&amp;mybody.html', destination: '/news', permanent: true },
      { source: '/q-love-sma-2023.html', destination: '/news', permanent: true },
      { source: '/imlek2023.html', destination: '/news', permanent: true },
      { source: '/be-kind-be-smart.html', destination: '/news', permanent: true },
      { source: '/newyeartk.html', destination: '/news', permanent: true },
      { source: '/seminarguru23.html', destination: '/news', permanent: true },
      { source: '/motherday-tkkmn1.html', destination: '/news', permanent: true },
      { source: '/natal-2022-tkkmn2.html', destination: '/news', permanent: true },
      { source: '/natal-2022-tkkmn13.html', destination: '/news', permanent: true },
      { source: '/fieldtripsd2022.html', destination: '/news', permanent: true },
      { source: '/baksos-cianjur2.html', destination: '/news', permanent: true },
      { source: '/baksos-cianjur.html', destination: '/news', permanent: true },
      { source: '/fieldtrip9-22.html', destination: '/news', permanent: true },
      { source: '/rumah-keramik.html', destination: '/news', permanent: true },
      { source: '/here-i-am.html', destination: '/news', permanent: true },
      { source: '/bye-bye-faver.html', destination: '/news', permanent: true },
      { source: '/harikathina-2566-BE.html', destination: '/news', permanent: true },
      { source: '/bbdansp-sma.html', destination: '/news', permanent: true },
      { source: '/art-day-tk-kemurnian-1-2.html', destination: '/news', permanent: true },
      { source: '/p5-smp.html', destination: '/news', permanent: true },
      { source: '/batikday.html', destination: '/news', permanent: true },
      { source: '/openhouse22.html', destination: '/news', permanent: true },
      { source: '/art-day-tk-kemurnian-3-september-2022.html', destination: '/news', permanent: true },
      { source: '/vaksinasi-sd-kemurnian-2-september-2022.html', destination: '/news', permanent: true },
      { source: '/marketday2.html', destination: '/news', permanent: true },
      { source: '/upcycling-workshop.html', destination: '/news', permanent: true },
      { source: '/5tips.html', destination: '/news', permanent: true },
      { source: '/perayaan-hutri-77.html', destination: '/news', permanent: true },
      { source: '/upacara-hutti22.html', destination: '/news', permanent: true },
      { source: '/mpls22.html', destination: '/news', permanent: true },
      { source: '/imlek2022.html', destination: '/news', permanent: true },
      { source: '/misa-natal-sma-kemurnian-2.html', destination: '/news', permanent: true },
      { source: '/vaksinasi-sd-kemurnian-2.html', destination: '/news', permanent: true },
      { source: '/protokol-kesehatan.html', destination: '/news', permanent: true },
      { source: '/ptm-sma-kemurnian-2.html', destination: '/news', permanent: true },
    ];
  },
};

export default nextConfig;
