import type { Metadata } from "next";
import { Merriweather, Raleway } from "next/font/google";
import "./globals.css";

// Components
import Navbar from "./components/Navbar"

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-merriweather",
});

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} ${raleway.variable} antialiased`}
      >
        <Navbar />    
        {children}
      </body>
    </html>
  );
}
