SET default_tablespace = '';
SET default_table_access_method = "heap";

-- Enrollment
CREATE TABLE IF NOT EXISTS "public"."enrollment" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" character varying,
    "image_url" "text",
    "date" "date",
    "body" "text",
    "image_path" "text"
);
ALTER TABLE "public"."enrollment" OWNER TO "postgres";
ALTER TABLE "public"."enrollment" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."enrollment_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY "public"."enrollment" ADD CONSTRAINT "enrollment_pkey" PRIMARY KEY ("id");

-- Fasilitas
CREATE TABLE IF NOT EXISTS "public"."fasilitas" (
    "id" bigint NOT NULL,
    "title" "text",
    "image_urls" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nama_sekolah" "text" NOT NULL,
    "storage_path" "text",
    "order" smallint
);
ALTER TABLE "public"."fasilitas" OWNER TO "postgres";
ALTER TABLE "public"."fasilitas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."fasilitas_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY "public"."fasilitas" ADD CONSTRAINT "fasilitas_pkey" PRIMARY KEY ("id");

-- Hero Sliders
CREATE TABLE IF NOT EXISTS "public"."hero_sliders" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "image_urls" "text",
    "order" integer,
    "header_text" "text",
    "href_text" "text",
    "mobile_image_urls" "text",
    "tablet_image_urls" "text",
    "button_text" "text"
);
ALTER TABLE "public"."hero_sliders" OWNER TO "postgres";
ALTER TABLE "public"."hero_sliders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."hero_sliders_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY "public"."hero_sliders" ADD CONSTRAINT "hero_sliders_pkey" PRIMARY KEY ("id");

-- Kurikulum
CREATE TABLE IF NOT EXISTS "public"."kurikulum" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" character varying,
    "body" "text",
    "order" smallint,
    "preview" "text"
);
ALTER TABLE "public"."kurikulum" OWNER TO "postgres";
ALTER TABLE "public"."kurikulum" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."kurkulum_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY "public"."kurikulum" ADD CONSTRAINT "kurkulum_pkey" PRIMARY KEY ("id");

-- News
CREATE TABLE IF NOT EXISTS "public"."news" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" character varying NOT NULL,
    "date" "date" NOT NULL,
    "image_urls" "text"[] NOT NULL,
    "body" "text" NOT NULL,
    "embed" "text",
    "from" "public"."news_from" NOT NULL,
    "storage_paths" "text"[]
);
ALTER TABLE "public"."news" OWNER TO "postgres";
ALTER TABLE "public"."news" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."news_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY "public"."news" ADD CONSTRAINT "news_pkey" PRIMARY KEY ("id");

-- Primary Schools
CREATE TABLE IF NOT EXISTS "public"."primary_schools" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nama_sekolah" "text"
);
ALTER TABLE "public"."primary_schools" OWNER TO "postgres";
ALTER TABLE "public"."primary_schools" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."primary_schools_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY "public"."primary_schools" ADD CONSTRAINT "primary_schools_pkey" PRIMARY KEY ("id");

-- Search Static
CREATE TABLE IF NOT EXISTS "public"."search_static" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text" NOT NULL,
    "url" "text" NOT NULL
);
ALTER TABLE "public"."search_static" OWNER TO "postgres";
ALTER TABLE ONLY "public"."search_static" ADD CONSTRAINT "search_static_pkey" PRIMARY KEY ("id");

-- User Roles
CREATE TABLE IF NOT EXISTS "public"."user_roles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "roles" "public"."role_enum"
);
ALTER TABLE "public"."user_roles" OWNER TO "postgres";
ALTER TABLE "public"."user_roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_roles_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY "public"."user_roles" ADD CONSTRAINT "user_roles_pkey" PRIMARY KEY ("id", "user_id");

-- Views (Must come after tables)
CREATE OR REPLACE VIEW "public"."search_index" AS
 SELECT "search_static"."title",
    "search_static"."url"
   FROM "public"."search_static"
UNION ALL
 SELECT "n"."title",
    ('/news-detail/'::"text" || "n"."id") AS "url"
   FROM "public"."news" "n"
UNION ALL
 SELECT "k"."title",
    ('/kurikulum/'::"text" || "k"."id") AS "url"
   FROM "public"."kurikulum" "k"
UNION ALL
 SELECT 'Enrollment'::"text" AS "title",
    '/enrollment'::"text" AS "url"
   FROM "public"."enrollment" "e";

ALTER VIEW "public"."search_index" OWNER TO "postgres";
