

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."news_from" AS ENUM (
    'TK Kemurnian',
    'SD Kemurnian',
    'SMP Kemurnian',
    'Kemurnian',
    'TK Kemurnian II',
    'SD Kemurnian II',
    'SMP Kemurnian II',
    'SMA Kemurnian II',
    'Kemurnian II',
    'TK Kemurnian III',
    'SD Kemurnian III',
    'Kemurnian III',
    'General'
);


ALTER TYPE "public"."news_from" OWNER TO "postgres";


CREATE TYPE "public"."role_enum" AS ENUM (
    'TK Kemurnian',
    'SD Kemurnian',
    'SMP Kemurnian',
    'Kemurnian',
    'TK Kemurnian II',
    'SD Kemurnian II',
    'SMP Kemurnian II',
    'SMA Kemurnian II',
    'Kemurnian II',
    'TK Kemurnian III',
    'SD Kemurnian III',
    'Kemurnian III',
    'Admin',
    'Editor'
);


ALTER TYPE "public"."role_enum" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."enrollment" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" character varying,
    "image_url" "text",
    "date" "date",
    "body" "text",
    "image_path" "text"
);


ALTER TABLE "public"."enrollment" OWNER TO "postgres";


ALTER TABLE "public"."enrollment" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."enrollment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."fasilitas" (
    "id" bigint NOT NULL,
    "title" "text",
    "image_urls" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nama_sekolah" "text" NOT NULL,
    "storage_path" "text",
    "order" smallint
);


ALTER TABLE "public"."fasilitas" OWNER TO "postgres";


ALTER TABLE "public"."fasilitas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."fasilitas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."hero_sliders" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "image_urls" "text",
    "order" integer,
    "header_text" "text",
    "href_text" "text",
    "mobile_image_urls" "text",
    "tablet_image_urls" "text",
    "button_text" "text"
);


ALTER TABLE "public"."hero_sliders" OWNER TO "postgres";


ALTER TABLE "public"."hero_sliders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."hero_sliders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."kurikulum" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" character varying,
    "body" "text",
    "order" smallint,
    "preview" "text"
);


ALTER TABLE "public"."kurikulum" OWNER TO "postgres";


ALTER TABLE "public"."kurikulum" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."kurkulum_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."news" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" character varying NOT NULL,
    "date" "date" NOT NULL,
    "image_urls" "text"[] NOT NULL,
    "body" "text" NOT NULL,
    "embed" "text",
    "from" "public"."news_from" NOT NULL,
    "storage_paths" "text"[]
);


ALTER TABLE "public"."news" OWNER TO "postgres";


ALTER TABLE "public"."news" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."news_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."primary_schools" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nama_sekolah" "text"
);


ALTER TABLE "public"."primary_schools" OWNER TO "postgres";


ALTER TABLE "public"."primary_schools" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."primary_schools_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."search_static" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text" NOT NULL,
    "url" "text" NOT NULL
);


ALTER TABLE "public"."search_static" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."search_index" AS
 SELECT "search_static"."title",
    "search_static"."url"
   FROM "public"."search_static"
UNION ALL
 SELECT "n"."title",
    ('/news-detail/'::"text" || "n"."id") AS "url"
   FROM "public"."news" "n"
UNION ALL
 SELECT "k"."title",
    ('/kurikulum/'::"text" || "k"."id") AS "url"
   FROM "public"."kurikulum" "k"
UNION ALL
 SELECT 'Enrollment'::"text" AS "title",
    '/enrollment'::"text" AS "url"
   FROM "public"."enrollment" "e";


ALTER VIEW "public"."search_index" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_roles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "roles" "public"."role_enum"
);


ALTER TABLE "public"."user_roles" OWNER TO "postgres";


ALTER TABLE "public"."user_roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."enrollment"
    ADD CONSTRAINT "enrollment_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fasilitas"
    ADD CONSTRAINT "fasilitas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hero_sliders"
    ADD CONSTRAINT "hero_sliders_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."kurikulum"
    ADD CONSTRAINT "kurkulum_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."primary_schools"
    ADD CONSTRAINT "primary_schools_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."search_static"
    ADD CONSTRAINT "search_static_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_pkey" PRIMARY KEY ("id", "user_id");



CREATE POLICY "Allow authenticated users to delete hero sliders" ON "public"."hero_sliders" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Allow authenticated users to insert hero sliders" ON "public"."hero_sliders" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Allow authenticated users to update hero sliders" ON "public"."hero_sliders" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow everyone to view hero sliders" ON "public"."hero_sliders" FOR SELECT USING (true);



CREATE POLICY "Allow public select on kurikulum" ON "public"."kurikulum" FOR SELECT USING (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."kurikulum" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "crud" ON "public"."fasilitas" TO "authenticated" USING (true);



CREATE POLICY "delete perm" ON "public"."kurikulum" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."enrollment" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fasilitas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hero_sliders" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."kurikulum" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."news" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "permission" ON "public"."kurikulum" TO "authenticated" USING (true);



CREATE POLICY "permission" ON "public"."news" TO "authenticated" USING (true);



ALTER TABLE "public"."primary_schools" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "public" ON "public"."fasilitas" FOR SELECT USING (true);



CREATE POLICY "read" ON "public"."enrollment" FOR SELECT USING (true);



CREATE POLICY "read" ON "public"."news" FOR SELECT USING (true);



CREATE POLICY "read public" ON "public"."search_static" FOR SELECT TO "anon" USING (true);



ALTER TABLE "public"."search_static" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "update" ON "public"."enrollment" FOR UPDATE TO "authenticated" USING (true);



ALTER TABLE "public"."user_roles" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."enrollment" TO "anon";
GRANT ALL ON TABLE "public"."enrollment" TO "authenticated";
GRANT ALL ON TABLE "public"."enrollment" TO "service_role";



GRANT ALL ON SEQUENCE "public"."enrollment_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."enrollment_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."enrollment_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."fasilitas" TO "anon";
GRANT ALL ON TABLE "public"."fasilitas" TO "authenticated";
GRANT ALL ON TABLE "public"."fasilitas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."fasilitas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."fasilitas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."fasilitas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."hero_sliders" TO "anon";
GRANT ALL ON TABLE "public"."hero_sliders" TO "authenticated";
GRANT ALL ON TABLE "public"."hero_sliders" TO "service_role";



GRANT ALL ON SEQUENCE "public"."hero_sliders_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."hero_sliders_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."hero_sliders_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."kurikulum" TO "anon";
GRANT ALL ON TABLE "public"."kurikulum" TO "authenticated";
GRANT ALL ON TABLE "public"."kurikulum" TO "service_role";



GRANT ALL ON SEQUENCE "public"."kurkulum_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."kurkulum_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."kurkulum_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."news" TO "anon";
GRANT ALL ON TABLE "public"."news" TO "authenticated";
GRANT ALL ON TABLE "public"."news" TO "service_role";



GRANT ALL ON SEQUENCE "public"."news_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."news_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."news_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."primary_schools" TO "anon";
GRANT ALL ON TABLE "public"."primary_schools" TO "authenticated";
GRANT ALL ON TABLE "public"."primary_schools" TO "service_role";



GRANT ALL ON SEQUENCE "public"."primary_schools_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."primary_schools_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."primary_schools_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."search_static" TO "anon";
GRANT ALL ON TABLE "public"."search_static" TO "authenticated";
GRANT ALL ON TABLE "public"."search_static" TO "service_role";



GRANT ALL ON TABLE "public"."search_index" TO "anon";
GRANT ALL ON TABLE "public"."search_index" TO "authenticated";
GRANT ALL ON TABLE "public"."search_index" TO "service_role";



GRANT ALL ON TABLE "public"."user_roles" TO "anon";
GRANT ALL ON TABLE "public"."user_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."user_roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_roles_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























drop extension if exists "pg_net";


  create policy "all 20edv_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'news'::text));



  create policy "all 20edv_1"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'news'::text));



  create policy "all 20edv_2"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'news'::text));



  create policy "all 20edv_3"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'news'::text));



  create policy "read 20edv_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'news'::text));



  create policy "rule"
  on "storage"."objects"
  as permissive
  for all
  to authenticated;



